### ISSUE TITLE
On the team selection page. When I click the big green bar nothing appears to happen. Can we make it indicate that the team has been chosen. 

### ISSUE THREAD

**Issue by mbardoe** [quadnix/gnhml#8]

**Comment by mbardoe** [comment]
This should lead to some screen that allows the coach to assign the rounds.

**Comment by mbardoe** [comment]
A team should not be allowed to have more than 5 players. When I switch the school the team members should clear out and I should be able to see players from that school.

**Comment by pkage** [comment]
new team selection page in the works, stand by

**Comment by pkage** [comment]
new team selection makes this issue obsolete
